// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMsg.proto

package com.zemel.data.proto.entiy;

public final class LoginMsg {
  private LoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code LoginMsg.LoginCmdType}
   */
  public enum LoginCmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    Msg(0),
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    Login(1),
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    NewFriend(3),
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    Error(4),
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    Ping(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    public static final int Msg_VALUE = 0;
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    public static final int Login_VALUE = 1;
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    public static final int NewFriend_VALUE = 3;
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    public static final int Error_VALUE = 4;
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    public static final int Ping_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LoginCmdType valueOf(int value) {
      return forNumber(value);
    }

    public static LoginCmdType forNumber(int value) {
      switch (value) {
        case 0: return Msg;
        case 1: return Login;
        case 3: return NewFriend;
        case 4: return Error;
        case 5: return Ping;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginCmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoginCmdType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginCmdType>() {
            public LoginCmdType findValueByNumber(int number) {
              return LoginCmdType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.LoginMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoginCmdType[] VALUES = values();

    public static LoginCmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LoginCmdType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoginMsg.LoginCmdType)
  }

  public interface PlayerInfoPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginMsg.PlayerInfoPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.LoginMsg.LoginCmdType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.LoginMsg.LoginCmdType type = 1;</code>
     */
    com.zemel.data.proto.entiy.LoginMsg.LoginCmdType getType();
  }
  /**
   * Protobuf type {@code LoginMsg.PlayerInfoPB}
   */
  public  static final class PlayerInfoPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginMsg.PlayerInfoPB)
      PlayerInfoPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerInfoPB.newBuilder() to construct.
    private PlayerInfoPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerInfoPB() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfoPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_PlayerInfoPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_PlayerInfoPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.class, com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.LoginMsg.LoginCmdType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.LoginMsg.LoginCmdType type = 1;</code>
     */
    public com.zemel.data.proto.entiy.LoginMsg.LoginCmdType getType() {
      com.zemel.data.proto.entiy.LoginMsg.LoginCmdType result = com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.valueOf(type_);
      return result == null ? com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.Msg.getNumber()) {
        output.writeEnum(1, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.Msg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB other = (com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginMsg.PlayerInfoPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginMsg.PlayerInfoPB)
        com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_PlayerInfoPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_PlayerInfoPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.class, com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_PlayerInfoPB_descriptor;
      }

      public com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB build() {
        com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB buildPartial() {
        com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB result = new com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB) {
          return mergeFrom((com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB other) {
        if (other == com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.LoginMsg.LoginCmdType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.LoginMsg.LoginCmdType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.LoginMsg.LoginCmdType type = 1;</code>
       */
      public com.zemel.data.proto.entiy.LoginMsg.LoginCmdType getType() {
        com.zemel.data.proto.entiy.LoginMsg.LoginCmdType result = com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.valueOf(type_);
        return result == null ? com.zemel.data.proto.entiy.LoginMsg.LoginCmdType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.LoginMsg.LoginCmdType type = 1;</code>
       */
      public Builder setType(com.zemel.data.proto.entiy.LoginMsg.LoginCmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.LoginMsg.LoginCmdType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginMsg.PlayerInfoPB)
    }

    // @@protoc_insertion_point(class_scope:LoginMsg.PlayerInfoPB)
    private static final com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB();
    }

    public static com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerInfoPB>
        PARSER = new com.google.protobuf.AbstractParser<PlayerInfoPB>() {
      public PlayerInfoPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerInfoPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerInfoPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfoPB> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.LoginMsg.PlayerInfoPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginMsgCSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginMsg.LoginMsgCS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *account name
     * </pre>
     *
     * <code>int32 userID = 1;</code>
     */
    int getUserID();

    /**
     * <pre>
     * nickname
     * </pre>
     *
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <pre>
     * nickname
     * </pre>
     *
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code LoginMsg.LoginMsgCS}
   */
  public  static final class LoginMsgCS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginMsg.LoginMsgCS)
      LoginMsgCSOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginMsgCS.newBuilder() to construct.
    private LoginMsgCS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginMsgCS() {
      userID_ = 0;
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginMsgCS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userID_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_LoginMsgCS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_LoginMsgCS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.class, com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userID_;
    /**
     * <pre>
     *account name
     * </pre>
     *
     * <code>int32 userID = 1;</code>
     */
    public int getUserID() {
      return userID_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     * nickname
     * </pre>
     *
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * nickname
     * </pre>
     *
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userID_ != 0) {
        output.writeInt32(1, userID_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userID_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS other = (com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS) obj;

      boolean result = true;
      result = result && (getUserID()
          == other.getUserID());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserID();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginMsg.LoginMsgCS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginMsg.LoginMsgCS)
        com.zemel.data.proto.entiy.LoginMsg.LoginMsgCSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_LoginMsgCS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_LoginMsgCS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.class, com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userID_ = 0;

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_LoginMsgCS_descriptor;
      }

      public com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS build() {
        com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS buildPartial() {
        com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS result = new com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS(this);
        result.userID_ = userID_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS) {
          return mergeFrom((com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS other) {
        if (other == com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS.getDefaultInstance()) return this;
        if (other.getUserID() != 0) {
          setUserID(other.getUserID());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userID_ ;
      /**
       * <pre>
       *account name
       * </pre>
       *
       * <code>int32 userID = 1;</code>
       */
      public int getUserID() {
        return userID_;
      }
      /**
       * <pre>
       *account name
       * </pre>
       *
       * <code>int32 userID = 1;</code>
       */
      public Builder setUserID(int value) {
        
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *account name
       * </pre>
       *
       * <code>int32 userID = 1;</code>
       */
      public Builder clearUserID() {
        
        userID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       * nickname
       * </pre>
       *
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * nickname
       * </pre>
       *
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * nickname
       * </pre>
       *
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nickname
       * </pre>
       *
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nickname
       * </pre>
       *
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginMsg.LoginMsgCS)
    }

    // @@protoc_insertion_point(class_scope:LoginMsg.LoginMsgCS)
    private static final com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS();
    }

    public static com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginMsgCS>
        PARSER = new com.google.protobuf.AbstractParser<LoginMsgCS>() {
      public LoginMsgCS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginMsgCS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginMsgCS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginMsgCS> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.LoginMsg.LoginMsgCS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginMsg.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code LoginMsg.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginMsg.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      uid_ = 0;
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.LoginMsg.User.class, com.zemel.data.proto.entiy.LoginMsg.User.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.LoginMsg.User)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.LoginMsg.User other = (com.zemel.data.proto.entiy.LoginMsg.User) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.LoginMsg.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginMsg.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginMsg.User)
        com.zemel.data.proto.entiy.LoginMsg.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.LoginMsg.User.class, com.zemel.data.proto.entiy.LoginMsg.User.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.LoginMsg.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_User_descriptor;
      }

      public com.zemel.data.proto.entiy.LoginMsg.User getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.LoginMsg.User.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.LoginMsg.User build() {
        com.zemel.data.proto.entiy.LoginMsg.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.LoginMsg.User buildPartial() {
        com.zemel.data.proto.entiy.LoginMsg.User result = new com.zemel.data.proto.entiy.LoginMsg.User(this);
        result.uid_ = uid_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.LoginMsg.User) {
          return mergeFrom((com.zemel.data.proto.entiy.LoginMsg.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.LoginMsg.User other) {
        if (other == com.zemel.data.proto.entiy.LoginMsg.User.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.LoginMsg.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.LoginMsg.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginMsg.User)
    }

    // @@protoc_insertion_point(class_scope:LoginMsg.User)
    private static final com.zemel.data.proto.entiy.LoginMsg.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.LoginMsg.User();
    }

    public static com.zemel.data.proto.entiy.LoginMsg.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.LoginMsg.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerLoginMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginMsg.ServerLoginMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serverId = 1;</code>
     */
    int getServerId();
  }
  /**
   * Protobuf type {@code LoginMsg.ServerLoginMsg}
   */
  public  static final class ServerLoginMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginMsg.ServerLoginMsg)
      ServerLoginMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerLoginMsg.newBuilder() to construct.
    private ServerLoginMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerLoginMsg() {
      serverId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerLoginMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_ServerLoginMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_ServerLoginMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.class, com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>int32 serverId = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeInt32(1, serverId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg other = (com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg) obj;

      boolean result = true;
      result = result && (getServerId()
          == other.getServerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginMsg.ServerLoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginMsg.ServerLoginMsg)
        com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_ServerLoginMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_ServerLoginMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.class, com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.LoginMsg.internal_static_LoginMsg_ServerLoginMsg_descriptor;
      }

      public com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg build() {
        com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg buildPartial() {
        com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg result = new com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg(this);
        result.serverId_ = serverId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg) {
          return mergeFrom((com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg other) {
        if (other == com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverId_ ;
      /**
       * <code>int32 serverId = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>int32 serverId = 1;</code>
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverId = 1;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginMsg.ServerLoginMsg)
    }

    // @@protoc_insertion_point(class_scope:LoginMsg.ServerLoginMsg)
    private static final com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg();
    }

    public static com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerLoginMsg>
        PARSER = new com.google.protobuf.AbstractParser<ServerLoginMsg>() {
      public ServerLoginMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerLoginMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerLoginMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerLoginMsg> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.LoginMsg.ServerLoginMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMsg_PlayerInfoPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginMsg_PlayerInfoPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMsg_LoginMsgCS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginMsg_LoginMsgCS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMsg_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginMsg_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMsg_ServerLoginMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginMsg_ServerLoginMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LoginMsg.proto\022\010LoginMsg\"4\n\014PlayerInfo" +
      "PB\022$\n\004type\030\001 \001(\0162\026.LoginMsg.LoginCmdType" +
      "\".\n\nLoginMsgCS\022\016\n\006userID\030\001 \001(\005\022\020\n\010passwo" +
      "rd\030\002 \001(\t\"%\n\004User\022\013\n\003uid\030\001 \001(\005\022\020\n\010passwor" +
      "d\030\002 \001(\t\"\"\n\016ServerLoginMsg\022\020\n\010serverId\030\001 " +
      "\001(\005*F\n\014LoginCmdType\022\007\n\003Msg\020\000\022\t\n\005Login\020\001\022" +
      "\r\n\tNewFriend\020\003\022\t\n\005Error\020\004\022\010\n\004Ping\020\005B\034\n\032c" +
      "om.zemel.data.proto.entiyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginMsg_PlayerInfoPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginMsg_PlayerInfoPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginMsg_PlayerInfoPB_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_LoginMsg_LoginMsgCS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginMsg_LoginMsgCS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginMsg_LoginMsgCS_descriptor,
        new java.lang.String[] { "UserID", "Password", });
    internal_static_LoginMsg_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LoginMsg_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginMsg_User_descriptor,
        new java.lang.String[] { "Uid", "Password", });
    internal_static_LoginMsg_ServerLoginMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LoginMsg_ServerLoginMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginMsg_ServerLoginMsg_descriptor,
        new java.lang.String[] { "ServerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
