// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneMsg.proto

package com.zemel.data.proto.entiy;

public final class SceneMsg {
  private SceneMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code SceneCmdType}
   */
  public enum SceneCmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UpdatePosition = 0;</code>
     */
    UpdatePosition(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UpdatePosition = 0;</code>
     */
    public static final int UpdatePosition_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SceneCmdType valueOf(int value) {
      return forNumber(value);
    }

    public static SceneCmdType forNumber(int value) {
      switch (value) {
        case 0: return UpdatePosition;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SceneCmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SceneCmdType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SceneCmdType>() {
            public SceneCmdType findValueByNumber(int number) {
              return SceneCmdType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.SceneMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final SceneCmdType[] VALUES = values();

    public static SceneCmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SceneCmdType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SceneCmdType)
  }

  public interface SceneMsgCSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SceneMsgCS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.SceneCmdType cmdType = 1;</code>
     */
    int getCmdTypeValue();
    /**
     * <code>.SceneCmdType cmdType = 1;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.SceneCmdType getCmdType();

    /**
     * <code>.TransformPB transform = 2;</code>
     */
    boolean hasTransform();
    /**
     * <code>.TransformPB transform = 2;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.TransformPB getTransform();
    /**
     * <code>.TransformPB transform = 2;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder getTransformOrBuilder();

    /**
     * <code>int32 playerID = 3;</code>
     */
    int getPlayerID();
  }
  /**
   * Protobuf type {@code SceneMsgCS}
   */
  public  static final class SceneMsgCS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SceneMsgCS)
      SceneMsgCSOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SceneMsgCS.newBuilder() to construct.
    private SceneMsgCS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SceneMsgCS() {
      cmdType_ = 0;
      playerID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SceneMsgCS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              cmdType_ = rawValue;
              break;
            }
            case 18: {
              com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder subBuilder = null;
              if (transform_ != null) {
                subBuilder = transform_.toBuilder();
              }
              transform_ = input.readMessage(com.zemel.data.proto.entiy.SceneMsg.TransformPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transform_);
                transform_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              playerID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_SceneMsgCS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_SceneMsgCS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.class, com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.Builder.class);
    }

    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_;
    /**
     * <code>.SceneCmdType cmdType = 1;</code>
     */
    public int getCmdTypeValue() {
      return cmdType_;
    }
    /**
     * <code>.SceneCmdType cmdType = 1;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.SceneCmdType getCmdType() {
      com.zemel.data.proto.entiy.SceneMsg.SceneCmdType result = com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.valueOf(cmdType_);
      return result == null ? com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.UNRECOGNIZED : result;
    }

    public static final int TRANSFORM_FIELD_NUMBER = 2;
    private com.zemel.data.proto.entiy.SceneMsg.TransformPB transform_;
    /**
     * <code>.TransformPB transform = 2;</code>
     */
    public boolean hasTransform() {
      return transform_ != null;
    }
    /**
     * <code>.TransformPB transform = 2;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.TransformPB getTransform() {
      return transform_ == null ? com.zemel.data.proto.entiy.SceneMsg.TransformPB.getDefaultInstance() : transform_;
    }
    /**
     * <code>.TransformPB transform = 2;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder getTransformOrBuilder() {
      return getTransform();
    }

    public static final int PLAYERID_FIELD_NUMBER = 3;
    private int playerID_;
    /**
     * <code>int32 playerID = 3;</code>
     */
    public int getPlayerID() {
      return playerID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdType_ != com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.UpdatePosition.getNumber()) {
        output.writeEnum(1, cmdType_);
      }
      if (transform_ != null) {
        output.writeMessage(2, getTransform());
      }
      if (playerID_ != 0) {
        output.writeInt32(3, playerID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdType_ != com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.UpdatePosition.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmdType_);
      }
      if (transform_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTransform());
      }
      if (playerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, playerID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS other = (com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS) obj;

      boolean result = true;
      result = result && cmdType_ == other.cmdType_;
      result = result && (hasTransform() == other.hasTransform());
      if (hasTransform()) {
        result = result && getTransform()
            .equals(other.getTransform());
      }
      result = result && (getPlayerID()
          == other.getPlayerID());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + cmdType_;
      if (hasTransform()) {
        hash = (37 * hash) + TRANSFORM_FIELD_NUMBER;
        hash = (53 * hash) + getTransform().hashCode();
      }
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SceneMsgCS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SceneMsgCS)
        com.zemel.data.proto.entiy.SceneMsg.SceneMsgCSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_SceneMsgCS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_SceneMsgCS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.class, com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdType_ = 0;

        if (transformBuilder_ == null) {
          transform_ = null;
        } else {
          transform_ = null;
          transformBuilder_ = null;
        }
        playerID_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_SceneMsgCS_descriptor;
      }

      public com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS build() {
        com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS buildPartial() {
        com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS result = new com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS(this);
        result.cmdType_ = cmdType_;
        if (transformBuilder_ == null) {
          result.transform_ = transform_;
        } else {
          result.transform_ = transformBuilder_.build();
        }
        result.playerID_ = playerID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS) {
          return mergeFrom((com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS other) {
        if (other == com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS.getDefaultInstance()) return this;
        if (other.cmdType_ != 0) {
          setCmdTypeValue(other.getCmdTypeValue());
        }
        if (other.hasTransform()) {
          mergeTransform(other.getTransform());
        }
        if (other.getPlayerID() != 0) {
          setPlayerID(other.getPlayerID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmdType_ = 0;
      /**
       * <code>.SceneCmdType cmdType = 1;</code>
       */
      public int getCmdTypeValue() {
        return cmdType_;
      }
      /**
       * <code>.SceneCmdType cmdType = 1;</code>
       */
      public Builder setCmdTypeValue(int value) {
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.SceneCmdType cmdType = 1;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.SceneCmdType getCmdType() {
        com.zemel.data.proto.entiy.SceneMsg.SceneCmdType result = com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.valueOf(cmdType_);
        return result == null ? com.zemel.data.proto.entiy.SceneMsg.SceneCmdType.UNRECOGNIZED : result;
      }
      /**
       * <code>.SceneCmdType cmdType = 1;</code>
       */
      public Builder setCmdType(com.zemel.data.proto.entiy.SceneMsg.SceneCmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmdType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.SceneCmdType cmdType = 1;</code>
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private com.zemel.data.proto.entiy.SceneMsg.TransformPB transform_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.TransformPB, com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder, com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder> transformBuilder_;
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public boolean hasTransform() {
        return transformBuilder_ != null || transform_ != null;
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.TransformPB getTransform() {
        if (transformBuilder_ == null) {
          return transform_ == null ? com.zemel.data.proto.entiy.SceneMsg.TransformPB.getDefaultInstance() : transform_;
        } else {
          return transformBuilder_.getMessage();
        }
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public Builder setTransform(com.zemel.data.proto.entiy.SceneMsg.TransformPB value) {
        if (transformBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transform_ = value;
          onChanged();
        } else {
          transformBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public Builder setTransform(
          com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder builderForValue) {
        if (transformBuilder_ == null) {
          transform_ = builderForValue.build();
          onChanged();
        } else {
          transformBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public Builder mergeTransform(com.zemel.data.proto.entiy.SceneMsg.TransformPB value) {
        if (transformBuilder_ == null) {
          if (transform_ != null) {
            transform_ =
              com.zemel.data.proto.entiy.SceneMsg.TransformPB.newBuilder(transform_).mergeFrom(value).buildPartial();
          } else {
            transform_ = value;
          }
          onChanged();
        } else {
          transformBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public Builder clearTransform() {
        if (transformBuilder_ == null) {
          transform_ = null;
          onChanged();
        } else {
          transform_ = null;
          transformBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder getTransformBuilder() {
        
        onChanged();
        return getTransformFieldBuilder().getBuilder();
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder getTransformOrBuilder() {
        if (transformBuilder_ != null) {
          return transformBuilder_.getMessageOrBuilder();
        } else {
          return transform_ == null ?
              com.zemel.data.proto.entiy.SceneMsg.TransformPB.getDefaultInstance() : transform_;
        }
      }
      /**
       * <code>.TransformPB transform = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.TransformPB, com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder, com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder> 
          getTransformFieldBuilder() {
        if (transformBuilder_ == null) {
          transformBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zemel.data.proto.entiy.SceneMsg.TransformPB, com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder, com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder>(
                  getTransform(),
                  getParentForChildren(),
                  isClean());
          transform_ = null;
        }
        return transformBuilder_;
      }

      private int playerID_ ;
      /**
       * <code>int32 playerID = 3;</code>
       */
      public int getPlayerID() {
        return playerID_;
      }
      /**
       * <code>int32 playerID = 3;</code>
       */
      public Builder setPlayerID(int value) {
        
        playerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerID = 3;</code>
       */
      public Builder clearPlayerID() {
        
        playerID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SceneMsgCS)
    }

    // @@protoc_insertion_point(class_scope:SceneMsgCS)
    private static final com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS();
    }

    public static com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneMsgCS>
        PARSER = new com.google.protobuf.AbstractParser<SceneMsgCS>() {
      public SceneMsgCS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SceneMsgCS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SceneMsgCS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneMsgCS> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.SceneMsg.SceneMsgCS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostionPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PostionPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     */
    float getZ();

    /**
     * <code>float w = 4;</code>
     */
    float getW();

    /**
     * <code>float vertical = 5;</code>
     */
    float getVertical();

    /**
     * <code>float horizontal = 6;</code>
     */
    float getHorizontal();
  }
  /**
   * Protobuf type {@code PostionPB}
   */
  public  static final class PostionPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PostionPB)
      PostionPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostionPB.newBuilder() to construct.
    private PostionPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostionPB() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
      w_ = 0F;
      vertical_ = 0F;
      horizontal_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostionPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            case 37: {

              w_ = input.readFloat();
              break;
            }
            case 45: {

              vertical_ = input.readFloat();
              break;
            }
            case 53: {

              horizontal_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_PostionPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_PostionPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.class, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int W_FIELD_NUMBER = 4;
    private float w_;
    /**
     * <code>float w = 4;</code>
     */
    public float getW() {
      return w_;
    }

    public static final int VERTICAL_FIELD_NUMBER = 5;
    private float vertical_;
    /**
     * <code>float vertical = 5;</code>
     */
    public float getVertical() {
      return vertical_;
    }

    public static final int HORIZONTAL_FIELD_NUMBER = 6;
    private float horizontal_;
    /**
     * <code>float horizontal = 6;</code>
     */
    public float getHorizontal() {
      return horizontal_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      if (w_ != 0F) {
        output.writeFloat(4, w_);
      }
      if (vertical_ != 0F) {
        output.writeFloat(5, vertical_);
      }
      if (horizontal_ != 0F) {
        output.writeFloat(6, horizontal_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (w_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, w_);
      }
      if (vertical_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, vertical_);
      }
      if (horizontal_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, horizontal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.SceneMsg.PostionPB)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.SceneMsg.PostionPB other = (com.zemel.data.proto.entiy.SceneMsg.PostionPB) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && (
          java.lang.Float.floatToIntBits(getW())
          == java.lang.Float.floatToIntBits(
              other.getW()));
      result = result && (
          java.lang.Float.floatToIntBits(getVertical())
          == java.lang.Float.floatToIntBits(
              other.getVertical()));
      result = result && (
          java.lang.Float.floatToIntBits(getHorizontal())
          == java.lang.Float.floatToIntBits(
              other.getHorizontal()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + W_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getW());
      hash = (37 * hash) + VERTICAL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVertical());
      hash = (37 * hash) + HORIZONTAL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHorizontal());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.SceneMsg.PostionPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PostionPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PostionPB)
        com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_PostionPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_PostionPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.SceneMsg.PostionPB.class, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.SceneMsg.PostionPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        w_ = 0F;

        vertical_ = 0F;

        horizontal_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_PostionPB_descriptor;
      }

      public com.zemel.data.proto.entiy.SceneMsg.PostionPB getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.SceneMsg.PostionPB build() {
        com.zemel.data.proto.entiy.SceneMsg.PostionPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.SceneMsg.PostionPB buildPartial() {
        com.zemel.data.proto.entiy.SceneMsg.PostionPB result = new com.zemel.data.proto.entiy.SceneMsg.PostionPB(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.w_ = w_;
        result.vertical_ = vertical_;
        result.horizontal_ = horizontal_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.SceneMsg.PostionPB) {
          return mergeFrom((com.zemel.data.proto.entiy.SceneMsg.PostionPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.SceneMsg.PostionPB other) {
        if (other == com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getW() != 0F) {
          setW(other.getW());
        }
        if (other.getVertical() != 0F) {
          setVertical(other.getVertical());
        }
        if (other.getHorizontal() != 0F) {
          setHorizontal(other.getHorizontal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.SceneMsg.PostionPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.SceneMsg.PostionPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float w_ ;
      /**
       * <code>float w = 4;</code>
       */
      public float getW() {
        return w_;
      }
      /**
       * <code>float w = 4;</code>
       */
      public Builder setW(float value) {
        
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float w = 4;</code>
       */
      public Builder clearW() {
        
        w_ = 0F;
        onChanged();
        return this;
      }

      private float vertical_ ;
      /**
       * <code>float vertical = 5;</code>
       */
      public float getVertical() {
        return vertical_;
      }
      /**
       * <code>float vertical = 5;</code>
       */
      public Builder setVertical(float value) {
        
        vertical_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float vertical = 5;</code>
       */
      public Builder clearVertical() {
        
        vertical_ = 0F;
        onChanged();
        return this;
      }

      private float horizontal_ ;
      /**
       * <code>float horizontal = 6;</code>
       */
      public float getHorizontal() {
        return horizontal_;
      }
      /**
       * <code>float horizontal = 6;</code>
       */
      public Builder setHorizontal(float value) {
        
        horizontal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float horizontal = 6;</code>
       */
      public Builder clearHorizontal() {
        
        horizontal_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PostionPB)
    }

    // @@protoc_insertion_point(class_scope:PostionPB)
    private static final com.zemel.data.proto.entiy.SceneMsg.PostionPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.SceneMsg.PostionPB();
    }

    public static com.zemel.data.proto.entiy.SceneMsg.PostionPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostionPB>
        PARSER = new com.google.protobuf.AbstractParser<PostionPB>() {
      public PostionPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PostionPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostionPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostionPB> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.SceneMsg.PostionPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransformPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransformPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.PostionPB position = 1;</code>
     */
    boolean hasPosition();
    /**
     * <code>.PostionPB position = 1;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPB getPosition();
    /**
     * <code>.PostionPB position = 1;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getPositionOrBuilder();

    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    boolean hasRotation();
    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPB getRotation();
    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getRotationOrBuilder();

    /**
     * <code>.PostionPB scale = 3;</code>
     */
    boolean hasScale();
    /**
     * <code>.PostionPB scale = 3;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPB getScale();
    /**
     * <code>.PostionPB scale = 3;</code>
     */
    com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getScaleOrBuilder();
  }
  /**
   * Protobuf type {@code TransformPB}
   */
  public  static final class TransformPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransformPB)
      TransformPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransformPB.newBuilder() to construct.
    private TransformPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransformPB() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransformPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(com.zemel.data.proto.entiy.SceneMsg.PostionPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder subBuilder = null;
              if (rotation_ != null) {
                subBuilder = rotation_.toBuilder();
              }
              rotation_ = input.readMessage(com.zemel.data.proto.entiy.SceneMsg.PostionPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rotation_);
                rotation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder subBuilder = null;
              if (scale_ != null) {
                subBuilder = scale_.toBuilder();
              }
              scale_ = input.readMessage(com.zemel.data.proto.entiy.SceneMsg.PostionPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(scale_);
                scale_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_TransformPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.SceneMsg.internal_static_TransformPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.SceneMsg.TransformPB.class, com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder.class);
    }

    public static final int POSITION_FIELD_NUMBER = 1;
    private com.zemel.data.proto.entiy.SceneMsg.PostionPB position_;
    /**
     * <code>.PostionPB position = 1;</code>
     */
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.PostionPB position = 1;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPB getPosition() {
      return position_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : position_;
    }
    /**
     * <code>.PostionPB position = 1;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int ROTATION_FIELD_NUMBER = 2;
    private com.zemel.data.proto.entiy.SceneMsg.PostionPB rotation_;
    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    public boolean hasRotation() {
      return rotation_ != null;
    }
    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPB getRotation() {
      return rotation_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : rotation_;
    }
    /**
     * <code>.PostionPB rotation = 2;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getRotationOrBuilder() {
      return getRotation();
    }

    public static final int SCALE_FIELD_NUMBER = 3;
    private com.zemel.data.proto.entiy.SceneMsg.PostionPB scale_;
    /**
     * <code>.PostionPB scale = 3;</code>
     */
    public boolean hasScale() {
      return scale_ != null;
    }
    /**
     * <code>.PostionPB scale = 3;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPB getScale() {
      return scale_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : scale_;
    }
    /**
     * <code>.PostionPB scale = 3;</code>
     */
    public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getScaleOrBuilder() {
      return getScale();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (position_ != null) {
        output.writeMessage(1, getPosition());
      }
      if (rotation_ != null) {
        output.writeMessage(2, getRotation());
      }
      if (scale_ != null) {
        output.writeMessage(3, getScale());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (rotation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRotation());
      }
      if (scale_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getScale());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.SceneMsg.TransformPB)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.SceneMsg.TransformPB other = (com.zemel.data.proto.entiy.SceneMsg.TransformPB) obj;

      boolean result = true;
      result = result && (hasPosition() == other.hasPosition());
      if (hasPosition()) {
        result = result && getPosition()
            .equals(other.getPosition());
      }
      result = result && (hasRotation() == other.hasRotation());
      if (hasRotation()) {
        result = result && getRotation()
            .equals(other.getRotation());
      }
      result = result && (hasScale() == other.hasScale());
      if (hasScale()) {
        result = result && getScale()
            .equals(other.getScale());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      if (hasRotation()) {
        hash = (37 * hash) + ROTATION_FIELD_NUMBER;
        hash = (53 * hash) + getRotation().hashCode();
      }
      if (hasScale()) {
        hash = (37 * hash) + SCALE_FIELD_NUMBER;
        hash = (53 * hash) + getScale().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.SceneMsg.TransformPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransformPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransformPB)
        com.zemel.data.proto.entiy.SceneMsg.TransformPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_TransformPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_TransformPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.SceneMsg.TransformPB.class, com.zemel.data.proto.entiy.SceneMsg.TransformPB.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.SceneMsg.TransformPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        if (rotationBuilder_ == null) {
          rotation_ = null;
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }
        if (scaleBuilder_ == null) {
          scale_ = null;
        } else {
          scale_ = null;
          scaleBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.SceneMsg.internal_static_TransformPB_descriptor;
      }

      public com.zemel.data.proto.entiy.SceneMsg.TransformPB getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.SceneMsg.TransformPB.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.SceneMsg.TransformPB build() {
        com.zemel.data.proto.entiy.SceneMsg.TransformPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.SceneMsg.TransformPB buildPartial() {
        com.zemel.data.proto.entiy.SceneMsg.TransformPB result = new com.zemel.data.proto.entiy.SceneMsg.TransformPB(this);
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        if (rotationBuilder_ == null) {
          result.rotation_ = rotation_;
        } else {
          result.rotation_ = rotationBuilder_.build();
        }
        if (scaleBuilder_ == null) {
          result.scale_ = scale_;
        } else {
          result.scale_ = scaleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.SceneMsg.TransformPB) {
          return mergeFrom((com.zemel.data.proto.entiy.SceneMsg.TransformPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.SceneMsg.TransformPB other) {
        if (other == com.zemel.data.proto.entiy.SceneMsg.TransformPB.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasRotation()) {
          mergeRotation(other.getRotation());
        }
        if (other.hasScale()) {
          mergeScale(other.getScale());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.SceneMsg.TransformPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.SceneMsg.TransformPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.zemel.data.proto.entiy.SceneMsg.PostionPB position_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> positionBuilder_;
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public Builder setPosition(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public Builder setPosition(
          com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public Builder mergePosition(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.PostionPB position = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private com.zemel.data.proto.entiy.SceneMsg.PostionPB rotation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> rotationBuilder_;
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public boolean hasRotation() {
        return rotationBuilder_ != null || rotation_ != null;
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB getRotation() {
        if (rotationBuilder_ == null) {
          return rotation_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : rotation_;
        } else {
          return rotationBuilder_.getMessage();
        }
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public Builder setRotation(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (rotationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rotation_ = value;
          onChanged();
        } else {
          rotationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public Builder setRotation(
          com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder builderForValue) {
        if (rotationBuilder_ == null) {
          rotation_ = builderForValue.build();
          onChanged();
        } else {
          rotationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public Builder mergeRotation(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (rotationBuilder_ == null) {
          if (rotation_ != null) {
            rotation_ =
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.newBuilder(rotation_).mergeFrom(value).buildPartial();
          } else {
            rotation_ = value;
          }
          onChanged();
        } else {
          rotationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public Builder clearRotation() {
        if (rotationBuilder_ == null) {
          rotation_ = null;
          onChanged();
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder getRotationBuilder() {
        
        onChanged();
        return getRotationFieldBuilder().getBuilder();
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getRotationOrBuilder() {
        if (rotationBuilder_ != null) {
          return rotationBuilder_.getMessageOrBuilder();
        } else {
          return rotation_ == null ?
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : rotation_;
        }
      }
      /**
       * <code>.PostionPB rotation = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> 
          getRotationFieldBuilder() {
        if (rotationBuilder_ == null) {
          rotationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder>(
                  getRotation(),
                  getParentForChildren(),
                  isClean());
          rotation_ = null;
        }
        return rotationBuilder_;
      }

      private com.zemel.data.proto.entiy.SceneMsg.PostionPB scale_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> scaleBuilder_;
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public boolean hasScale() {
        return scaleBuilder_ != null || scale_ != null;
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB getScale() {
        if (scaleBuilder_ == null) {
          return scale_ == null ? com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : scale_;
        } else {
          return scaleBuilder_.getMessage();
        }
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public Builder setScale(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (scaleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scale_ = value;
          onChanged();
        } else {
          scaleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public Builder setScale(
          com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder builderForValue) {
        if (scaleBuilder_ == null) {
          scale_ = builderForValue.build();
          onChanged();
        } else {
          scaleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public Builder mergeScale(com.zemel.data.proto.entiy.SceneMsg.PostionPB value) {
        if (scaleBuilder_ == null) {
          if (scale_ != null) {
            scale_ =
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.newBuilder(scale_).mergeFrom(value).buildPartial();
          } else {
            scale_ = value;
          }
          onChanged();
        } else {
          scaleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public Builder clearScale() {
        if (scaleBuilder_ == null) {
          scale_ = null;
          onChanged();
        } else {
          scale_ = null;
          scaleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder getScaleBuilder() {
        
        onChanged();
        return getScaleFieldBuilder().getBuilder();
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      public com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder getScaleOrBuilder() {
        if (scaleBuilder_ != null) {
          return scaleBuilder_.getMessageOrBuilder();
        } else {
          return scale_ == null ?
              com.zemel.data.proto.entiy.SceneMsg.PostionPB.getDefaultInstance() : scale_;
        }
      }
      /**
       * <code>.PostionPB scale = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder> 
          getScaleFieldBuilder() {
        if (scaleBuilder_ == null) {
          scaleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zemel.data.proto.entiy.SceneMsg.PostionPB, com.zemel.data.proto.entiy.SceneMsg.PostionPB.Builder, com.zemel.data.proto.entiy.SceneMsg.PostionPBOrBuilder>(
                  getScale(),
                  getParentForChildren(),
                  isClean());
          scale_ = null;
        }
        return scaleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransformPB)
    }

    // @@protoc_insertion_point(class_scope:TransformPB)
    private static final com.zemel.data.proto.entiy.SceneMsg.TransformPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.SceneMsg.TransformPB();
    }

    public static com.zemel.data.proto.entiy.SceneMsg.TransformPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransformPB>
        PARSER = new com.google.protobuf.AbstractParser<TransformPB>() {
      public TransformPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransformPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransformPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransformPB> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.SceneMsg.TransformPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SceneMsgCS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SceneMsgCS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostionPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostionPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransformPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransformPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016SceneMsg.proto\"_\n\nSceneMsgCS\022\036\n\007cmdTyp" +
      "e\030\001 \001(\0162\r.SceneCmdType\022\037\n\ttransform\030\002 \001(" +
      "\0132\014.TransformPB\022\020\n\010playerID\030\003 \001(\005\"]\n\tPos" +
      "tionPB\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022" +
      "\t\n\001w\030\004 \001(\002\022\020\n\010vertical\030\005 \001(\002\022\022\n\nhorizont" +
      "al\030\006 \001(\002\"d\n\013TransformPB\022\034\n\010position\030\001 \001(" +
      "\0132\n.PostionPB\022\034\n\010rotation\030\002 \001(\0132\n.Postio" +
      "nPB\022\031\n\005scale\030\003 \001(\0132\n.PostionPB*\"\n\014SceneC" +
      "mdType\022\022\n\016UpdatePosition\020\000B\034\n\032com.zemel." +
      "data.proto.entiyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SceneMsgCS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SceneMsgCS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SceneMsgCS_descriptor,
        new java.lang.String[] { "CmdType", "Transform", "PlayerID", });
    internal_static_PostionPB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PostionPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostionPB_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "W", "Vertical", "Horizontal", });
    internal_static_TransformPB_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TransformPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransformPB_descriptor,
        new java.lang.String[] { "Position", "Rotation", "Scale", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
