// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestABean.proto

package com.zemel.data.proto.entiy;

public final class TestABean {
  private TestABean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestABeanPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestABeanPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int64 aId = 2;</code>
     */
    long getAId();

    /**
     * <code>int32 bid = 3;</code>
     */
    int getBid();

    /**
     * <code>string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated string names = 5;</code>
     */
    java.util.List<java.lang.String>
        getNamesList();
    /**
     * <code>repeated string names = 5;</code>
     */
    int getNamesCount();
    /**
     * <code>repeated string names = 5;</code>
     */
    java.lang.String getNames(int index);
    /**
     * <code>repeated string names = 5;</code>
     */
    com.google.protobuf.ByteString
        getNamesBytes(int index);

    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> 
        getBBeanList();
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBBean(int index);
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    int getBBeanCount();
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
        getBBeanOrBuilderList();
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBBeanOrBuilder(
        int index);

    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> 
        getBbbBeanList();
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBbbBean(int index);
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    int getBbbBeanCount();
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
        getBbbBeanOrBuilderList();
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBbbBeanOrBuilder(
        int index);

    /**
     * <code>repeated int32 hah = 8;</code>
     */
    java.util.List<java.lang.Integer> getHahList();
    /**
     * <code>repeated int32 hah = 8;</code>
     */
    int getHahCount();
    /**
     * <code>repeated int32 hah = 8;</code>
     */
    int getHah(int index);
  }
  /**
   * Protobuf type {@code TestABeanPB}
   */
  public  static final class TestABeanPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestABeanPB)
      TestABeanPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestABeanPB.newBuilder() to construct.
    private TestABeanPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestABeanPB() {
      id_ = 0;
      aId_ = 0L;
      bid_ = 0;
      name_ = "";
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bBean_ = java.util.Collections.emptyList();
      bbbBean_ = java.util.Collections.emptyList();
      hah_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestABeanPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              aId_ = input.readInt64();
              break;
            }
            case 24: {

              bid_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                names_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              names_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                bBean_ = new java.util.ArrayList<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB>();
                mutable_bitField0_ |= 0x00000020;
              }
              bBean_.add(
                  input.readMessage(com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                bbbBean_ = new java.util.ArrayList<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB>();
                mutable_bitField0_ |= 0x00000040;
              }
              bbbBean_.add(
                  input.readMessage(com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.parser(), extensionRegistry));
              break;
            }
            case 64: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                hah_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              hah_.add(input.readInt32());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
                hah_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                hah_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          names_ = names_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          bBean_ = java.util.Collections.unmodifiableList(bBean_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          bbbBean_ = java.util.Collections.unmodifiableList(bbbBean_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          hah_ = java.util.Collections.unmodifiableList(hah_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.TestABean.internal_static_TestABeanPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.TestABean.internal_static_TestABeanPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.TestABean.TestABeanPB.class, com.zemel.data.proto.entiy.TestABean.TestABeanPB.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int AID_FIELD_NUMBER = 2;
    private long aId_;
    /**
     * <code>int64 aId = 2;</code>
     */
    public long getAId() {
      return aId_;
    }

    public static final int BID_FIELD_NUMBER = 3;
    private int bid_;
    /**
     * <code>int32 bid = 3;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAMES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList names_;
    /**
     * <code>repeated string names = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNamesList() {
      return names_;
    }
    /**
     * <code>repeated string names = 5;</code>
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated string names = 5;</code>
     */
    public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated string names = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }

    public static final int BBEAN_FIELD_NUMBER = 6;
    private java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> bBean_;
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> getBBeanList() {
      return bBean_;
    }
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    public java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
        getBBeanOrBuilderList() {
      return bBean_;
    }
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    public int getBBeanCount() {
      return bBean_.size();
    }
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBBean(int index) {
      return bBean_.get(index);
    }
    /**
     * <code>repeated .TestBBeanPB bBean = 6;</code>
     */
    public com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBBeanOrBuilder(
        int index) {
      return bBean_.get(index);
    }

    public static final int BBBBEAN_FIELD_NUMBER = 7;
    private java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> bbbBean_;
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> getBbbBeanList() {
      return bbbBean_;
    }
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    public java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
        getBbbBeanOrBuilderList() {
      return bbbBean_;
    }
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    public int getBbbBeanCount() {
      return bbbBean_.size();
    }
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBbbBean(int index) {
      return bbbBean_.get(index);
    }
    /**
     * <code>repeated .TestBBeanPB bbbBean = 7;</code>
     */
    public com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBbbBeanOrBuilder(
        int index) {
      return bbbBean_.get(index);
    }

    public static final int HAH_FIELD_NUMBER = 8;
    private java.util.List<java.lang.Integer> hah_;
    /**
     * <code>repeated int32 hah = 8;</code>
     */
    public java.util.List<java.lang.Integer>
        getHahList() {
      return hah_;
    }
    /**
     * <code>repeated int32 hah = 8;</code>
     */
    public int getHahCount() {
      return hah_.size();
    }
    /**
     * <code>repeated int32 hah = 8;</code>
     */
    public int getHah(int index) {
      return hah_.get(index);
    }
    private int hahMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (aId_ != 0L) {
        output.writeInt64(2, aId_);
      }
      if (bid_ != 0) {
        output.writeInt32(3, bid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      for (int i = 0; i < names_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, names_.getRaw(i));
      }
      for (int i = 0; i < bBean_.size(); i++) {
        output.writeMessage(6, bBean_.get(i));
      }
      for (int i = 0; i < bbbBean_.size(); i++) {
        output.writeMessage(7, bbbBean_.get(i));
      }
      if (getHahList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(hahMemoizedSerializedSize);
      }
      for (int i = 0; i < hah_.size(); i++) {
        output.writeInt32NoTag(hah_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (aId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, aId_);
      }
      if (bid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < names_.size(); i++) {
          dataSize += computeStringSizeNoTag(names_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNamesList().size();
      }
      for (int i = 0; i < bBean_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, bBean_.get(i));
      }
      for (int i = 0; i < bbbBean_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, bbbBean_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hah_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(hah_.get(i));
        }
        size += dataSize;
        if (!getHahList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        hahMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.TestABean.TestABeanPB)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.TestABean.TestABeanPB other = (com.zemel.data.proto.entiy.TestABean.TestABeanPB) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getAId()
          == other.getAId());
      result = result && (getBid()
          == other.getBid());
      result = result && getName()
          .equals(other.getName());
      result = result && getNamesList()
          .equals(other.getNamesList());
      result = result && getBBeanList()
          .equals(other.getBBeanList());
      result = result && getBbbBeanList()
          .equals(other.getBbbBeanList());
      result = result && getHahList()
          .equals(other.getHahList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAId());
      hash = (37 * hash) + BID_FIELD_NUMBER;
      hash = (53 * hash) + getBid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getNamesCount() > 0) {
        hash = (37 * hash) + NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getNamesList().hashCode();
      }
      if (getBBeanCount() > 0) {
        hash = (37 * hash) + BBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getBBeanList().hashCode();
      }
      if (getBbbBeanCount() > 0) {
        hash = (37 * hash) + BBBBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getBbbBeanList().hashCode();
      }
      if (getHahCount() > 0) {
        hash = (37 * hash) + HAH_FIELD_NUMBER;
        hash = (53 * hash) + getHahList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.TestABean.TestABeanPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestABeanPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestABeanPB)
        com.zemel.data.proto.entiy.TestABean.TestABeanPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.TestABean.internal_static_TestABeanPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.TestABean.internal_static_TestABeanPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.TestABean.TestABeanPB.class, com.zemel.data.proto.entiy.TestABean.TestABeanPB.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.TestABean.TestABeanPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBBeanFieldBuilder();
          getBbbBeanFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        aId_ = 0L;

        bid_ = 0;

        name_ = "";

        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (bBeanBuilder_ == null) {
          bBean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          bBeanBuilder_.clear();
        }
        if (bbbBeanBuilder_ == null) {
          bbbBean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          bbbBeanBuilder_.clear();
        }
        hah_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.TestABean.internal_static_TestABeanPB_descriptor;
      }

      public com.zemel.data.proto.entiy.TestABean.TestABeanPB getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.TestABean.TestABeanPB.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.TestABean.TestABeanPB build() {
        com.zemel.data.proto.entiy.TestABean.TestABeanPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.TestABean.TestABeanPB buildPartial() {
        com.zemel.data.proto.entiy.TestABean.TestABeanPB result = new com.zemel.data.proto.entiy.TestABean.TestABeanPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.aId_ = aId_;
        result.bid_ = bid_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          names_ = names_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.names_ = names_;
        if (bBeanBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            bBean_ = java.util.Collections.unmodifiableList(bBean_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.bBean_ = bBean_;
        } else {
          result.bBean_ = bBeanBuilder_.build();
        }
        if (bbbBeanBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            bbbBean_ = java.util.Collections.unmodifiableList(bbbBean_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.bbbBean_ = bbbBean_;
        } else {
          result.bbbBean_ = bbbBeanBuilder_.build();
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          hah_ = java.util.Collections.unmodifiableList(hah_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.hah_ = hah_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.TestABean.TestABeanPB) {
          return mergeFrom((com.zemel.data.proto.entiy.TestABean.TestABeanPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.TestABean.TestABeanPB other) {
        if (other == com.zemel.data.proto.entiy.TestABean.TestABeanPB.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAId() != 0L) {
          setAId(other.getAId());
        }
        if (other.getBid() != 0) {
          setBid(other.getBid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.names_.isEmpty()) {
          if (names_.isEmpty()) {
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureNamesIsMutable();
            names_.addAll(other.names_);
          }
          onChanged();
        }
        if (bBeanBuilder_ == null) {
          if (!other.bBean_.isEmpty()) {
            if (bBean_.isEmpty()) {
              bBean_ = other.bBean_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureBBeanIsMutable();
              bBean_.addAll(other.bBean_);
            }
            onChanged();
          }
        } else {
          if (!other.bBean_.isEmpty()) {
            if (bBeanBuilder_.isEmpty()) {
              bBeanBuilder_.dispose();
              bBeanBuilder_ = null;
              bBean_ = other.bBean_;
              bitField0_ = (bitField0_ & ~0x00000020);
              bBeanBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBBeanFieldBuilder() : null;
            } else {
              bBeanBuilder_.addAllMessages(other.bBean_);
            }
          }
        }
        if (bbbBeanBuilder_ == null) {
          if (!other.bbbBean_.isEmpty()) {
            if (bbbBean_.isEmpty()) {
              bbbBean_ = other.bbbBean_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureBbbBeanIsMutable();
              bbbBean_.addAll(other.bbbBean_);
            }
            onChanged();
          }
        } else {
          if (!other.bbbBean_.isEmpty()) {
            if (bbbBeanBuilder_.isEmpty()) {
              bbbBeanBuilder_.dispose();
              bbbBeanBuilder_ = null;
              bbbBean_ = other.bbbBean_;
              bitField0_ = (bitField0_ & ~0x00000040);
              bbbBeanBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBbbBeanFieldBuilder() : null;
            } else {
              bbbBeanBuilder_.addAllMessages(other.bbbBean_);
            }
          }
        }
        if (!other.hah_.isEmpty()) {
          if (hah_.isEmpty()) {
            hah_ = other.hah_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureHahIsMutable();
            hah_.addAll(other.hah_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.TestABean.TestABeanPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.TestABean.TestABeanPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private long aId_ ;
      /**
       * <code>int64 aId = 2;</code>
       */
      public long getAId() {
        return aId_;
      }
      /**
       * <code>int64 aId = 2;</code>
       */
      public Builder setAId(long value) {
        
        aId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 aId = 2;</code>
       */
      public Builder clearAId() {
        
        aId_ = 0L;
        onChanged();
        return this;
      }

      private int bid_ ;
      /**
       * <code>int32 bid = 3;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>int32 bid = 3;</code>
       */
      public Builder setBid(int value) {
        
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bid = 3;</code>
       */
      public Builder clearBid() {
        
        bid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNamesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          names_ = new com.google.protobuf.LazyStringArrayList(names_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNamesList() {
        return names_.getUnmodifiableView();
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public int getNamesCount() {
        return names_.size();
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public java.lang.String getNames(int index) {
        return names_.get(index);
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNamesBytes(int index) {
        return names_.getByteString(index);
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public Builder setNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public Builder addNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public Builder addAllNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, names_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public Builder clearNames() {
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 5;</code>
       */
      public Builder addNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> bBean_ =
        java.util.Collections.emptyList();
      private void ensureBBeanIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          bBean_ = new java.util.ArrayList<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB>(bBean_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> bBeanBuilder_;

      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> getBBeanList() {
        if (bBeanBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bBean_);
        } else {
          return bBeanBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public int getBBeanCount() {
        if (bBeanBuilder_ == null) {
          return bBean_.size();
        } else {
          return bBeanBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBBean(int index) {
        if (bBeanBuilder_ == null) {
          return bBean_.get(index);
        } else {
          return bBeanBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder setBBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBBeanIsMutable();
          bBean_.set(index, value);
          onChanged();
        } else {
          bBeanBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder setBBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bBeanBuilder_ == null) {
          ensureBBeanIsMutable();
          bBean_.set(index, builderForValue.build());
          onChanged();
        } else {
          bBeanBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder addBBean(com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBBeanIsMutable();
          bBean_.add(value);
          onChanged();
        } else {
          bBeanBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder addBBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBBeanIsMutable();
          bBean_.add(index, value);
          onChanged();
        } else {
          bBeanBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder addBBean(
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bBeanBuilder_ == null) {
          ensureBBeanIsMutable();
          bBean_.add(builderForValue.build());
          onChanged();
        } else {
          bBeanBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder addBBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bBeanBuilder_ == null) {
          ensureBBeanIsMutable();
          bBean_.add(index, builderForValue.build());
          onChanged();
        } else {
          bBeanBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder addAllBBean(
          java.lang.Iterable<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> values) {
        if (bBeanBuilder_ == null) {
          ensureBBeanIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bBean_);
          onChanged();
        } else {
          bBeanBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder clearBBean() {
        if (bBeanBuilder_ == null) {
          bBean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          bBeanBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public Builder removeBBean(int index) {
        if (bBeanBuilder_ == null) {
          ensureBBeanIsMutable();
          bBean_.remove(index);
          onChanged();
        } else {
          bBeanBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder getBBeanBuilder(
          int index) {
        return getBBeanFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBBeanOrBuilder(
          int index) {
        if (bBeanBuilder_ == null) {
          return bBean_.get(index);  } else {
          return bBeanBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
           getBBeanOrBuilderList() {
        if (bBeanBuilder_ != null) {
          return bBeanBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bBean_);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder addBBeanBuilder() {
        return getBBeanFieldBuilder().addBuilder(
            com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.getDefaultInstance());
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder addBBeanBuilder(
          int index) {
        return getBBeanFieldBuilder().addBuilder(
            index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.getDefaultInstance());
      }
      /**
       * <code>repeated .TestBBeanPB bBean = 6;</code>
       */
      public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder> 
           getBBeanBuilderList() {
        return getBBeanFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
          getBBeanFieldBuilder() {
        if (bBeanBuilder_ == null) {
          bBeanBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder>(
                  bBean_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          bBean_ = null;
        }
        return bBeanBuilder_;
      }

      private java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> bbbBean_ =
        java.util.Collections.emptyList();
      private void ensureBbbBeanIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          bbbBean_ = new java.util.ArrayList<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB>(bbbBean_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> bbbBeanBuilder_;

      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> getBbbBeanList() {
        if (bbbBeanBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bbbBean_);
        } else {
          return bbbBeanBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public int getBbbBeanCount() {
        if (bbbBeanBuilder_ == null) {
          return bbbBean_.size();
        } else {
          return bbbBeanBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB getBbbBean(int index) {
        if (bbbBeanBuilder_ == null) {
          return bbbBean_.get(index);
        } else {
          return bbbBeanBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder setBbbBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bbbBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBbbBeanIsMutable();
          bbbBean_.set(index, value);
          onChanged();
        } else {
          bbbBeanBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder setBbbBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bbbBeanBuilder_ == null) {
          ensureBbbBeanIsMutable();
          bbbBean_.set(index, builderForValue.build());
          onChanged();
        } else {
          bbbBeanBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder addBbbBean(com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bbbBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBbbBeanIsMutable();
          bbbBean_.add(value);
          onChanged();
        } else {
          bbbBeanBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder addBbbBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB value) {
        if (bbbBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBbbBeanIsMutable();
          bbbBean_.add(index, value);
          onChanged();
        } else {
          bbbBeanBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder addBbbBean(
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bbbBeanBuilder_ == null) {
          ensureBbbBeanIsMutable();
          bbbBean_.add(builderForValue.build());
          onChanged();
        } else {
          bbbBeanBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder addBbbBean(
          int index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder builderForValue) {
        if (bbbBeanBuilder_ == null) {
          ensureBbbBeanIsMutable();
          bbbBean_.add(index, builderForValue.build());
          onChanged();
        } else {
          bbbBeanBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder addAllBbbBean(
          java.lang.Iterable<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPB> values) {
        if (bbbBeanBuilder_ == null) {
          ensureBbbBeanIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bbbBean_);
          onChanged();
        } else {
          bbbBeanBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder clearBbbBean() {
        if (bbbBeanBuilder_ == null) {
          bbbBean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          bbbBeanBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public Builder removeBbbBean(int index) {
        if (bbbBeanBuilder_ == null) {
          ensureBbbBeanIsMutable();
          bbbBean_.remove(index);
          onChanged();
        } else {
          bbbBeanBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder getBbbBeanBuilder(
          int index) {
        return getBbbBeanFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder getBbbBeanOrBuilder(
          int index) {
        if (bbbBeanBuilder_ == null) {
          return bbbBean_.get(index);  } else {
          return bbbBeanBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public java.util.List<? extends com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
           getBbbBeanOrBuilderList() {
        if (bbbBeanBuilder_ != null) {
          return bbbBeanBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bbbBean_);
        }
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder addBbbBeanBuilder() {
        return getBbbBeanFieldBuilder().addBuilder(
            com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.getDefaultInstance());
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder addBbbBeanBuilder(
          int index) {
        return getBbbBeanFieldBuilder().addBuilder(
            index, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.getDefaultInstance());
      }
      /**
       * <code>repeated .TestBBeanPB bbbBean = 7;</code>
       */
      public java.util.List<com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder> 
           getBbbBeanBuilderList() {
        return getBbbBeanFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder> 
          getBbbBeanFieldBuilder() {
        if (bbbBeanBuilder_ == null) {
          bbbBeanBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zemel.data.proto.entiy.TestBBean.TestBBeanPB, com.zemel.data.proto.entiy.TestBBean.TestBBeanPB.Builder, com.zemel.data.proto.entiy.TestBBean.TestBBeanPBOrBuilder>(
                  bbbBean_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          bbbBean_ = null;
        }
        return bbbBeanBuilder_;
      }

      private java.util.List<java.lang.Integer> hah_ = java.util.Collections.emptyList();
      private void ensureHahIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          hah_ = new java.util.ArrayList<java.lang.Integer>(hah_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public java.util.List<java.lang.Integer>
          getHahList() {
        return java.util.Collections.unmodifiableList(hah_);
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public int getHahCount() {
        return hah_.size();
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public int getHah(int index) {
        return hah_.get(index);
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public Builder setHah(
          int index, int value) {
        ensureHahIsMutable();
        hah_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public Builder addHah(int value) {
        ensureHahIsMutable();
        hah_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public Builder addAllHah(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureHahIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hah_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hah = 8;</code>
       */
      public Builder clearHah() {
        hah_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestABeanPB)
    }

    // @@protoc_insertion_point(class_scope:TestABeanPB)
    private static final com.zemel.data.proto.entiy.TestABean.TestABeanPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.TestABean.TestABeanPB();
    }

    public static com.zemel.data.proto.entiy.TestABean.TestABeanPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestABeanPB>
        PARSER = new com.google.protobuf.AbstractParser<TestABeanPB>() {
      public TestABeanPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestABeanPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestABeanPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestABeanPB> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.TestABean.TestABeanPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestABeanPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestABeanPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TestABean.proto\032\017TestBBean.proto\"\231\001\n\013T" +
      "estABeanPB\022\n\n\002id\030\001 \001(\005\022\013\n\003aId\030\002 \001(\003\022\013\n\003b" +
      "id\030\003 \001(\005\022\014\n\004name\030\004 \001(\t\022\r\n\005names\030\005 \003(\t\022\033\n" +
      "\005bBean\030\006 \003(\0132\014.TestBBeanPB\022\035\n\007bbbBean\030\007 " +
      "\003(\0132\014.TestBBeanPB\022\013\n\003hah\030\010 \003(\005B\034\n\032com.ze" +
      "mel.data.proto.entiyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zemel.data.proto.entiy.TestBBean.getDescriptor(),
        }, assigner);
    internal_static_TestABeanPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestABeanPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestABeanPB_descriptor,
        new java.lang.String[] { "Id", "AId", "Bid", "Name", "Names", "BBean", "BbbBean", "Hah", });
    com.zemel.data.proto.entiy.TestBBean.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
