// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebServerMsg.proto

package com.zemel.data.proto.entiy;

public final class WebServerMsg {
  private WebServerMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    Msg(0),
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    Login(1),
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    NewFriend(3),
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    Error(4),
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    Ping(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    public static final int Msg_VALUE = 0;
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    public static final int Login_VALUE = 1;
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    public static final int NewFriend_VALUE = 3;
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    public static final int Error_VALUE = 4;
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    public static final int Ping_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return Msg;
        case 1: return Login;
        case 3: return NewFriend;
        case 4: return Error;
        case 5: return Ping;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.WebServerMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface NotifyWebServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotifyWebServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType type = 1;</code>
     */
    com.zemel.data.proto.entiy.WebServerMsg.MessageType getType();

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code NotifyWebServer}
   */
  public  static final class NotifyWebServer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NotifyWebServer)
      NotifyWebServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NotifyWebServer.newBuilder() to construct.
    private NotifyWebServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotifyWebServer() {
      type_ = 0;
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyWebServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemel.data.proto.entiy.WebServerMsg.internal_static_NotifyWebServer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemel.data.proto.entiy.WebServerMsg.internal_static_NotifyWebServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.class, com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType type = 1;</code>
     */
    public com.zemel.data.proto.entiy.WebServerMsg.MessageType getType() {
      com.zemel.data.proto.entiy.WebServerMsg.MessageType result = com.zemel.data.proto.entiy.WebServerMsg.MessageType.valueOf(type_);
      return result == null ? com.zemel.data.proto.entiy.WebServerMsg.MessageType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.zemel.data.proto.entiy.WebServerMsg.MessageType.Msg.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.zemel.data.proto.entiy.WebServerMsg.MessageType.Msg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer)) {
        return super.equals(obj);
      }
      com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer other = (com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotifyWebServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotifyWebServer)
        com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zemel.data.proto.entiy.WebServerMsg.internal_static_NotifyWebServer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zemel.data.proto.entiy.WebServerMsg.internal_static_NotifyWebServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.class, com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.Builder.class);
      }

      // Construct using com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zemel.data.proto.entiy.WebServerMsg.internal_static_NotifyWebServer_descriptor;
      }

      public com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer getDefaultInstanceForType() {
        return com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.getDefaultInstance();
      }

      public com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer build() {
        com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer buildPartial() {
        com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer result = new com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer(this);
        result.type_ = type_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer) {
          return mergeFrom((com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer other) {
        if (other == com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessageType type = 1;</code>
       */
      public com.zemel.data.proto.entiy.WebServerMsg.MessageType getType() {
        com.zemel.data.proto.entiy.WebServerMsg.MessageType result = com.zemel.data.proto.entiy.WebServerMsg.MessageType.valueOf(type_);
        return result == null ? com.zemel.data.proto.entiy.WebServerMsg.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessageType type = 1;</code>
       */
      public Builder setType(com.zemel.data.proto.entiy.WebServerMsg.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NotifyWebServer)
    }

    // @@protoc_insertion_point(class_scope:NotifyWebServer)
    private static final com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer();
    }

    public static com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyWebServer>
        PARSER = new com.google.protobuf.AbstractParser<NotifyWebServer>() {
      public NotifyWebServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NotifyWebServer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotifyWebServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyWebServer> getParserForType() {
      return PARSER;
    }

    public com.zemel.data.proto.entiy.WebServerMsg.NotifyWebServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotifyWebServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NotifyWebServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022WebServerMsg.proto\"9\n\017NotifyWebServer\022" +
      "\032\n\004type\030\001 \001(\0162\014.MessageType\022\n\n\002id\030\002 \001(\005*" +
      "E\n\013MessageType\022\007\n\003Msg\020\000\022\t\n\005Login\020\001\022\r\n\tNe" +
      "wFriend\020\003\022\t\n\005Error\020\004\022\010\n\004Ping\020\005B\034\n\032com.ze" +
      "mel.data.proto.entiyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NotifyWebServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotifyWebServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NotifyWebServer_descriptor,
        new java.lang.String[] { "Type", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
