spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
  cache:
    ehcache:
      config: classpath:/ehcache.xml

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
