server:
  port: 8081
  workerId: 1
  decenterId: 2
  dev: false
  host: https://www.strhjd.com
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_server1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: zemel1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**

isNotIntercept: false

