server:
  port: 8080
  workerId: 1
  decenterId: 3
  dev: false
  host: www.chenshixin.cn
  tomcat:
    max-http-form-post-size: 10240
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: false
FileConfig:
  fileDir: /web1/data/resources/
  fileDownLoad: /image/
  resourcesPath: http://www.chenshixin.cn/resources/

IngotConfig:
  ingot: /diy/getDiyById/**,/upload,/system/**,/project/getProject/**

