server:
  port: 8084
  workerId: 1
  decenterId: 4
  dev: true
  host:
  tomcat:
    max-http-form-post-size: 10240
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
FileConfig:
  fileDir: F:\code\Z01\server\z01\web1\src\main\resources\static\image\
  fileDownLoad: /image/
  resourcesPath:

IngotConfig:
  ingot: /core/**,